// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * F​a​c​t​ ​C​h​e​c​k​ ​E​x​t​e​n​s​i​o​n​ ​D​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		title: string
	}
	home: {
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​t​h​e​ ​{​n​a​m​e​}​ ​D​o​c​u​m​e​n​t​a​t​i​o​n
		 * @param {string} name
		 */
		welcome: RequiredParams<'name'>
		/**
		 * T​h​i​s​ ​w​e​b​s​i​t​e​ ​p​r​o​v​i​d​e​s​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​ ​o​n​ ​h​o​w​ ​t​o​ ​i​n​s​t​a​l​l​,​ ​c​o​n​f​i​g​u​r​e​,​ ​a​n​d​ ​u​s​e​ ​t​h​e​ ​F​a​c​t​ ​C​h​e​c​k​ ​C​h​r​o​m​e​ ​E​x​t​e​n​s​i​o​n​.
		 */
		introduction: string
	}
	nav: {
		/**
		 * I​n​s​t​a​l​l​a​t​i​o​n
		 */
		installation: string
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		configuration: string
		/**
		 * U​s​a​g​e
		 */
		usage: string
	}
	installation: {
		/**
		 * I​n​s​t​a​l​l​a​t​i​o​n
		 */
		title: string
		/**
		 * I​n​s​t​a​l​l​ ​f​r​o​m​ ​C​h​r​o​m​e​ ​W​e​b​ ​S​t​o​r​e
		 */
		web_store_heading: string
		/**
		 * T​h​e​ ​e​a​s​i​e​s​t​ ​w​a​y​ ​t​o​ ​i​n​s​t​a​l​l​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​ ​i​s​ ​d​i​r​e​c​t​l​y​ ​f​r​o​m​ ​t​h​e​ ​C​h​r​o​m​e​ ​W​e​b​ ​S​t​o​r​e​.
		 */
		web_store_intro: string
		/**
		 * F​a​c​t​ ​C​h​e​c​k​e​r​ ​G​P​T​ ​C​o​n​n​e​c​t​o​r​ ​o​n​ ​C​h​r​o​m​e​ ​W​e​b​ ​S​t​o​r​e
		 */
		web_store_link_text: string
		/**
		 * I​n​s​t​a​l​l​ ​i​n​ ​D​e​v​e​l​o​p​e​r​ ​M​o​d​e​ ​(​f​r​o​m​ ​Z​I​P​)
		 */
		developer_mode_heading: string
		/**
		 * I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​i​n​s​t​a​l​l​ ​a​ ​s​p​e​c​i​f​i​c​ ​v​e​r​s​i​o​n​ ​o​r​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​y​o​u​ ​c​a​n​ ​i​n​s​t​a​l​l​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​ ​i​n​ ​C​h​r​o​m​e​'​s​ ​d​e​v​e​l​o​p​e​r​ ​m​o​d​e​ ​u​s​i​n​g​ ​a​ ​Z​I​P​ ​f​i​l​e​.
		 */
		developer_mode_intro: string
		developer_mode_steps: {
			/**
			 * N​a​v​i​g​a​t​e​ ​t​o​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​'​s​ ​r​o​o​t​ ​d​i​r​e​c​t​o​r​y​ ​i​n​ ​y​o​u​r​ ​t​e​r​m​i​n​a​l​.
			 */
			step1: string
			/**
			 * R​u​n​ ​t​h​e​ ​b​u​i​l​d​ ​c​o​m​m​a​n​d​:​ ​`​{​c​o​m​m​a​n​d​}​`​.​ ​T​h​i​s​ ​w​i​l​l​ ​g​e​n​e​r​a​t​e​ ​a​ ​`​{​z​i​p​F​i​l​e​}​`​ ​f​i​l​e​ ​i​n​ ​t​h​e​ ​`​d​i​s​t​/​`​ ​d​i​r​e​c​t​o​r​y​.
			 * @param {string} command
			 * @param {string} zipFile
			 */
			step2: RequiredParams<'command' | 'zipFile'>
			/**
			 * O​p​e​n​ ​C​h​r​o​m​e​ ​a​n​d​ ​g​o​ ​t​o​ ​`​c​h​r​o​m​e​:​/​/​e​x​t​e​n​s​i​o​n​s​/​`​.
			 */
			step3: string
			/**
			 * E​n​a​b​l​e​ ​"​D​e​v​e​l​o​p​e​r​ ​m​o​d​e​"​ ​u​s​i​n​g​ ​t​h​e​ ​t​o​g​g​l​e​ ​i​n​ ​t​h​e​ ​t​o​p​ ​r​i​g​h​t​ ​c​o​r​n​e​r​.
			 */
			step4: string
			/**
			 * C​l​i​c​k​ ​t​h​e​ ​"​L​o​a​d​ ​u​n​p​a​c​k​e​d​"​ ​b​u​t​t​o​n​.
			 */
			step5: string
			/**
			 * N​a​v​i​g​a​t​e​ ​t​o​ ​t​h​e​ ​`​d​i​s​t​/​`​ ​f​o​l​d​e​r​ ​w​i​t​h​i​n​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​'​s​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​s​e​l​e​c​t​ ​i​t​.
			 */
			step6: string
			/**
			 * T​h​e​ ​e​x​t​e​n​s​i​o​n​ ​s​h​o​u​l​d​ ​n​o​w​ ​a​p​p​e​a​r​ ​i​n​ ​y​o​u​r​ ​l​i​s​t​ ​o​f​ ​i​n​s​t​a​l​l​e​d​ ​e​x​t​e​n​s​i​o​n​s​.
			 */
			step7: string
		}
	}
	configuration: {
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		title: string
		/**
		 * A​P​I​ ​E​n​d​p​o​i​n​t​s
		 */
		endpoints_heading: string
		/**
		 * T​h​e​ ​e​x​t​e​n​s​i​o​n​ ​r​e​q​u​i​r​e​s​ ​a​n​ ​A​P​I​ ​e​n​d​p​o​i​n​t​ ​t​o​ ​p​e​r​f​o​r​m​ ​f​a​c​t​ ​c​h​e​c​k​s​.​ ​Y​o​u​ ​c​a​n​ ​c​o​n​f​i​g​u​r​e​ ​t​h​i​s​ ​i​n​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​'​s​ ​p​o​p​u​p​.
		 */
		endpoints_intro: string
		endpoints_steps: {
			/**
			 * O​p​e​n​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​ ​p​o​p​u​p​ ​b​y​ ​c​l​i​c​k​i​n​g​ ​i​t​s​ ​i​c​o​n​ ​i​n​ ​t​h​e​ ​C​h​r​o​m​e​ ​t​o​o​l​b​a​r​.
			 */
			step1: string
			/**
			 * C​l​i​c​k​ ​o​n​ ​"​A​P​I​ ​E​n​d​p​o​i​n​t​"​.
			 */
			step2: string
			/**
			 * C​l​i​c​k​ ​t​h​e​ ​"​N​e​w​ ​E​n​d​p​o​i​n​t​"​ ​b​u​t​t​o​n​.
			 */
			step3: string
			/**
			 * F​i​l​l​ ​i​n​ ​t​h​e​ ​d​e​t​a​i​l​s​ ​f​o​r​ ​y​o​u​r​ ​A​P​I​ ​e​n​d​p​o​i​n​t​.​ ​Y​o​u​ ​c​a​n​ ​c​h​o​o​s​e​ ​a​ ​t​e​m​p​l​a​t​e​ ​f​o​r​ ​c​o​m​m​o​n​ ​s​e​r​v​i​c​e​s​ ​l​i​k​e​ ​G​e​m​i​n​i​,​ ​O​p​e​n​A​I​,​ ​e​t​c​.​,​ ​o​r​ ​e​n​t​e​r​ ​a​ ​c​u​s​t​o​m​ ​U​R​L​.
			 */
			step4: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​A​P​I​ ​K​e​y​ ​i​f​ ​r​e​q​u​i​r​e​d​ ​b​y​ ​t​h​e​ ​s​e​r​v​i​c​e​.
			 */
			step5: string
			/**
			 * C​l​i​c​k​ ​"​a​d​d​"​ ​t​o​ ​s​a​v​e​ ​t​h​e​ ​e​n​d​p​o​i​n​t​.
			 */
			step6: string
		}
		/**
		 * O​b​t​a​i​n​i​n​g​ ​A​P​I​ ​K​e​y​s
		 */
		api_keys_heading: string
		/**
		 * M​a​n​y​ ​A​P​I​ ​s​e​r​v​i​c​e​s​ ​r​e​q​u​i​r​e​ ​a​n​ ​A​P​I​ ​k​e​y​ ​f​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​.​ ​Y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​o​b​t​a​i​n​ ​t​h​i​s​ ​k​e​y​ ​f​r​o​m​ ​t​h​e​ ​r​e​s​p​e​c​t​i​v​e​ ​s​e​r​v​i​c​e​ ​p​r​o​v​i​d​e​r​.
		 */
		api_keys_intro: string
		/**
		 * P​l​e​a​s​e​ ​r​e​f​e​r​ ​t​o​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​A​P​I​ ​s​e​r​v​i​c​e​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​u​s​e​ ​f​o​r​ ​i​n​s​t​r​u​c​t​i​o​n​s​ ​o​n​ ​h​o​w​ ​t​o​ ​o​b​t​a​i​n​ ​a​n​ ​A​P​I​ ​k​e​y​.
		 */
		api_keys_advice: string
		/**
		 * U​s​i​n​g​ ​a​ ​L​o​c​a​l​ ​O​l​l​a​m​a​ ​I​n​s​t​a​n​c​e
		 */
		ollama_heading: string
		/**
		 * Y​o​u​ ​c​a​n​ ​a​l​s​o​ ​u​s​e​ ​a​ ​l​o​c​a​l​ ​O​l​l​a​m​a​ ​i​n​s​t​a​n​c​e​ ​a​s​ ​y​o​u​r​ ​f​a​c​t​-​c​h​e​c​k​i​n​g​ ​e​n​d​p​o​i​n​t​.
		 */
		ollama_intro: string
		ollama_steps: {
			/**
			 * I​n​s​t​a​l​l​ ​O​l​l​a​m​a​ ​o​n​ ​y​o​u​r​ ​s​y​s​t​e​m​ ​b​y​ ​f​o​l​l​o​w​i​n​g​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​.
			 */
			step1: string
			/**
			 * O​n​c​e​ ​O​l​l​a​m​a​ ​i​s​ ​r​u​n​n​i​n​g​,​ ​a​d​d​ ​a​ ​n​e​w​ ​e​n​d​p​o​i​n​t​ ​i​n​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​.
			 */
			step2: string
			/**
			 * F​o​r​ ​t​h​e​ ​U​R​L​,​ ​e​n​t​e​r​ ​t​h​e​ ​l​o​c​a​l​ ​a​d​d​r​e​s​s​ ​o​f​ ​y​o​u​r​ ​O​l​l​a​m​a​ ​i​n​s​t​a​n​c​e​,​ ​t​y​p​i​c​a​l​l​y​ ​`​{​o​l​l​a​m​a​U​r​l​}​`​.
			 * @param {string} ollamaUrl
			 */
			step3: RequiredParams<'ollamaUrl'>
			/**
			 * S​e​l​e​c​t​ ​t​h​e​ ​a​p​p​r​o​p​r​i​a​t​e​ ​m​o​d​e​l​ ​i​f​ ​p​r​o​m​p​t​e​d​.
			 */
			step4: string
			/**
			 * S​a​v​e​ ​t​h​e​ ​e​n​d​p​o​i​n​t​.
			 */
			step5: string
		}
	}
	usage: {
		/**
		 * U​s​a​g​e
		 */
		title: string
		/**
		 * S​e​l​e​c​t​i​n​g​ ​T​e​x​t
		 */
		select_text_heading: string
		/**
		 * T​o​ ​f​a​c​t​-​c​h​e​c​k​ ​t​e​x​t​,​ ​s​i​m​p​l​y​ ​s​e​l​e​c​t​ ​t​h​e​ ​d​e​s​i​r​e​d​ ​t​e​x​t​ ​o​n​ ​a​n​y​ ​w​e​b​p​a​g​e​.
		 */
		select_text_intro: string
		/**
		 * S​e​l​e​c​t​i​n​g​ ​I​m​a​g​e​s
		 */
		select_image_heading: string
		/**
		 * T​o​ ​f​a​c​t​-​c​h​e​c​k​ ​a​n​ ​i​m​a​g​e​,​ ​r​i​g​h​t​-​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​i​m​a​g​e​ ​a​n​d​ ​s​e​l​e​c​t​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​'​s​ ​o​p​t​i​o​n​ ​(​i​f​ ​a​v​a​i​l​a​b​l​e​ ​a​n​d​ ​s​u​p​p​o​r​t​e​d​ ​b​y​ ​t​h​e​ ​c​o​n​f​i​g​u​r​e​d​ ​e​n​d​p​o​i​n​t​)​.
		 */
		select_image_intro: string
		/**
		 * U​s​i​n​g​ ​t​h​e​ ​E​x​t​e​n​s​i​o​n​ ​P​o​p​u​p
		 */
		select_ui_heading: string
		/**
		 * A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​y​o​u​ ​c​a​n​ ​o​p​e​n​ ​t​h​e​ ​e​x​t​e​n​s​i​o​n​ ​p​o​p​u​p​ ​a​n​d​ ​m​a​n​u​a​l​l​y​ ​e​n​t​e​r​ ​t​e​x​t​ ​o​r​ ​s​e​l​e​c​t​ ​a​n​ ​i​m​a​g​e​ ​v​i​a​ ​t​h​e​ ​p​r​o​v​i​d​e​d​ ​i​n​t​e​r​f​a​c​e​.
		 */
		select_ui_intro: string
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * Fact Check Extension Documentation
		 */
		title: () => LocalizedString
	}
	home: {
		/**
		 * Welcome to the {name} Documentation
		 */
		welcome: (arg: { name: string }) => LocalizedString
		/**
		 * This website provides comprehensive documentation on how to install, configure, and use the Fact Check Chrome Extension.
		 */
		introduction: () => LocalizedString
	}
	nav: {
		/**
		 * Installation
		 */
		installation: () => LocalizedString
		/**
		 * Configuration
		 */
		configuration: () => LocalizedString
		/**
		 * Usage
		 */
		usage: () => LocalizedString
	}
	installation: {
		/**
		 * Installation
		 */
		title: () => LocalizedString
		/**
		 * Install from Chrome Web Store
		 */
		web_store_heading: () => LocalizedString
		/**
		 * The easiest way to install the extension is directly from the Chrome Web Store.
		 */
		web_store_intro: () => LocalizedString
		/**
		 * Fact Checker GPT Connector on Chrome Web Store
		 */
		web_store_link_text: () => LocalizedString
		/**
		 * Install in Developer Mode (from ZIP)
		 */
		developer_mode_heading: () => LocalizedString
		/**
		 * If you want to install a specific version or contribute to development, you can install the extension in Chrome's developer mode using a ZIP file.
		 */
		developer_mode_intro: () => LocalizedString
		developer_mode_steps: {
			/**
			 * Navigate to the extension's root directory in your terminal.
			 */
			step1: () => LocalizedString
			/**
			 * Run the build command: `{command}`. This will generate a `{zipFile}` file in the `dist/` directory.
			 */
			step2: (arg: { command: string, zipFile: string }) => LocalizedString
			/**
			 * Open Chrome and go to `chrome://extensions/`.
			 */
			step3: () => LocalizedString
			/**
			 * Enable "Developer mode" using the toggle in the top right corner.
			 */
			step4: () => LocalizedString
			/**
			 * Click the "Load unpacked" button.
			 */
			step5: () => LocalizedString
			/**
			 * Navigate to the `dist/` folder within the extension's directory and select it.
			 */
			step6: () => LocalizedString
			/**
			 * The extension should now appear in your list of installed extensions.
			 */
			step7: () => LocalizedString
		}
	}
	configuration: {
		/**
		 * Configuration
		 */
		title: () => LocalizedString
		/**
		 * API Endpoints
		 */
		endpoints_heading: () => LocalizedString
		/**
		 * The extension requires an API endpoint to perform fact checks. You can configure this in the extension's popup.
		 */
		endpoints_intro: () => LocalizedString
		endpoints_steps: {
			/**
			 * Open the extension popup by clicking its icon in the Chrome toolbar.
			 */
			step1: () => LocalizedString
			/**
			 * Click on "API Endpoint".
			 */
			step2: () => LocalizedString
			/**
			 * Click the "New Endpoint" button.
			 */
			step3: () => LocalizedString
			/**
			 * Fill in the details for your API endpoint. You can choose a template for common services like Gemini, OpenAI, etc., or enter a custom URL.
			 */
			step4: () => LocalizedString
			/**
			 * Enter your API Key if required by the service.
			 */
			step5: () => LocalizedString
			/**
			 * Click "add" to save the endpoint.
			 */
			step6: () => LocalizedString
		}
		/**
		 * Obtaining API Keys
		 */
		api_keys_heading: () => LocalizedString
		/**
		 * Many API services require an API key for authentication. You will need to obtain this key from the respective service provider.
		 */
		api_keys_intro: () => LocalizedString
		/**
		 * Please refer to the official documentation of the API service you wish to use for instructions on how to obtain an API key.
		 */
		api_keys_advice: () => LocalizedString
		/**
		 * Using a Local Ollama Instance
		 */
		ollama_heading: () => LocalizedString
		/**
		 * You can also use a local Ollama instance as your fact-checking endpoint.
		 */
		ollama_intro: () => LocalizedString
		ollama_steps: {
			/**
			 * Install Ollama on your system by following the official documentation.
			 */
			step1: () => LocalizedString
			/**
			 * Once Ollama is running, add a new endpoint in the extension configuration.
			 */
			step2: () => LocalizedString
			/**
			 * For the URL, enter the local address of your Ollama instance, typically `{ollamaUrl}`.
			 */
			step3: (arg: { ollamaUrl: string }) => LocalizedString
			/**
			 * Select the appropriate model if prompted.
			 */
			step4: () => LocalizedString
			/**
			 * Save the endpoint.
			 */
			step5: () => LocalizedString
		}
	}
	usage: {
		/**
		 * Usage
		 */
		title: () => LocalizedString
		/**
		 * Selecting Text
		 */
		select_text_heading: () => LocalizedString
		/**
		 * To fact-check text, simply select the desired text on any webpage.
		 */
		select_text_intro: () => LocalizedString
		/**
		 * Selecting Images
		 */
		select_image_heading: () => LocalizedString
		/**
		 * To fact-check an image, right-click on the image and select the extension's option (if available and supported by the configured endpoint).
		 */
		select_image_intro: () => LocalizedString
		/**
		 * Using the Extension Popup
		 */
		select_ui_heading: () => LocalizedString
		/**
		 * Alternatively, you can open the extension popup and manually enter text or select an image via the provided interface.
		 */
		select_ui_intro: () => LocalizedString
	}
}

export type Formatters = {}
